jobs:
  include:
    - stage: test
      name: "Test java build"
      language: java
      jdk: openjdk8
      script:
        - java -version

    - stage: test
      name: "Test frontend build"
      language: node_js
      node_js:
        - "8"
      script:
        - npm -v
        - yarn -v
        
    - stage: release
      name: "Release latest"
      language: bash
      script:
        - docker version
    
    - stage: release
      name: "Release by tag"
      language: bash
      if: tag IS present
      script:
        - docker version
        
notifications:
  email: false
