jobs:
  include:
    - stage: test
      name: "Test backend"
      language: java
      jdk: openjdk8
      cache:
        directories:
          - .autoconf
          - $HOME/.m2
      script:
        - java -version
        - mkdir -p target && echo "Build success" > target/build.log
        
    - stage: test
      name: "Test frontend"
      language: node_js
      node_js:
        - "8"
      cache:
        directories:
          - frontend/node_modules
      before_script:
        - cd frontend
      script:
        - npm -v
        - yarn -v
        - echo "Build success" > build.log
        
    - stage: package
      name: "Package frontend and backend"
      language: bash
      script:
        - cat target/build.log
        - cat frontend/dist/build.log
        - echo "Package success" > package.log
        
    - stage: release
      name: "Release latest"
      language: bash
      script:
        - docker version
        - cat package.log
    
    - stage: release
      name: "Release the artifact by tag"
      language: bash
      if: tag IS present
      script:
        - docker version
        
notifications:
  email: false
