cache:
  directories:
  - target
  - frotend
  
jobs:
  include:
    - stage: test
      name: "Test backend"
      language: java
      jdk: openjdk8
      script:
        - java -version
        - mkdir -p target
        - echo "Build success" > target/build.log
        
    - stage: test
      name: "Test frontend"
      language: node_js
      node_js:
        - "8"
      cache:
        npm: true
      script:
        - npm -v
        - yarn -v
        - mkdir -p frontend
        - echo "Build success" > frontend/build.log
        
    - stage: release
      name: "Release latest"
      language: bash
      script:
        - docker version
        - cat target/build.log
        - cat frontend/build.log
    
    - stage: release
      name: "Release the artifact by tag"
      language: bash
      if: tag IS present
      script:
        - docker version
        
notifications:
  email: false
